### PR TITLE
added device list to DevicesIntro page

### PR DESCRIPTION
**Pull request by afmckinney**
- [ ] PR has tests / docs demo, and is linted.
- [ ] Commit and PR titles begin with [ComponentName], and are in imperative form: "[Component] Fix leaky abstraction".
- [ ] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (http://tr.im/vFqem).

### CODE REVIEW

**Comment by ewpatton** [comment]
Hi Andrew,

Can you rebase this change on the current master so we can merge it?

Thanks,
Evan

**Comment by marksherman** [comment]
I'm going to deal with it as soon as we get the other outstanding stuff in

**Comment by marksherman** [comment]
I rebased and force pushed onto this branch. @afmckinney please validate (and be careful, this will need a force pull or a fresh local branch)

@ewpatton if you could glance at it for sanity, I'd appreciate it.

In the rebase the file move had to be implemented as a delete and an add, but it works.

**Review by ewpatton — APPROVED** [review]
CSS of the table needs some adjustment but it isn't a blocker at this point. LTGM otherwise.

**Pull request merged**
