### PR TITLE
Fixed the spaceing and image ratios on tutorials and howtos pages.

### PR DESCRIPTION
**Pull request by afmckinney**
- [ ] PR has tests / docs demo, and is linted.
- [ ] Commit and PR titles begin with [ComponentName], and are in imperative form: "[Component] Fix leaky abstraction".
- [ ] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (http://tr.im/vFqem).

### CODE REVIEW

**Comment by halatmit** [comment]
I built this and it looks OK, but I don't know what I should be looking for or how it changes things.   What should I be seeing that's different from before?

**Comment by afmckinney** [comment]
Images change to the size of the device better.

**Comment by halatmit** [comment]
I don't think this is correct.   I you go to the howtos page and make it very wide, then the images get stretched wide and become distorted.

**Comment by afmckinney** [comment]
I'll take another look at this.

**Pull request closed without merging**
