### PR TITLE
Update extensions and Arduino 101 documentation

### PR DESCRIPTION
**Pull request by ewpatton**
Completed the draft documentation for all of the Arduino 101 extensions.

### CODE REVIEW

**Comment by ewpatton** [comment]
I've added another commit with compiled versions of the extensions that fix a handful of bugs reported by the beta tester community. Once this is merged and deployed I can put up a post detailing the fixes to the forum.

**Comment by afmckinney** [comment]
This looks great thank you for changing the links to the resources folder.

**Comment by afmckinney** [comment]
LGTM

**Review by afmckinney — COMMENTED** [review]
LGTM

**Pull request merged**
