### PR TITLE
Fix bug in sound recorder and associated documentation

### PR DESCRIPTION
**Pull request by ewpatton**
This PR provides a change to the sound recorder documentation that swaps the Play and Record pins to match the Grove documentation.

### CODE REVIEW

**Comment by marksherman** [comment]
Looks good from a technical standpoint (site and page builds and renders) but the word "becomes" may not be necessary for D4, as it no longer changes. Or some other better-explaining rewrite.

In my opinion, Good Enough to merge now and flag for rewrite later.

**Comment by ewpatton** [comment]
@marksherman The pin number is an integer and the goal is to imply that D4 is not an integer (but is what is labeled on the board) and 4 is. Also to differentiate that the pin is a digital pin and not, say, A2, which would be analog.

**Comment by marksherman** [comment]
Sounds sufficiently reasonable to me

**Comment by marksherman** [comment]
Mike checked the new binary file, so all is good.

**Pull request merged**
